### ISSUE TITLE
Question about the release date of AGORA 2

### ISSUE THREAD

**Issue by yhbae6022** [VirtualMetabolicHuman/AGORA#8]
Hi,

First of all, thank you for developing and maintaining this valuable database.
I really appreciate efforts of your team.

AGORA 1.03 supports 818 species, so I hope that the number of supported species will increase.
I expect this hope will be fulfilled in AGORA 2, which supports 1,644 species.

I wonder when these AGORA 2 DB will be released.

Best regards,
Young-Ho

**Comment by nick-youngblut** [comment]
I have the same question: are there any updates on the AGORA 2 DB release date?

**Comment by ithiele** [comment]
It has been released and can be found here: 

https://vmh.life/files/reconstructions/AGORA2/version2.01/

Please cite when using in full or in part: https://www.nature.com/articles/s41587-022-01628-0
