### ISSUE TITLE
Downloading an AGORA model

### ISSUE THREAD

**Issue by shumantov** [VirtualMetabolicHuman/AGORA#9]
Hi, 

Was wandering whether it's possible to download a metabolic model reconstruction from the AGORA repository. 
I aim at using this model for comparing with my models, via MEMOTE. If so, how do I do it? 

A following question - are all models in AGORA written in MATLAB format?

Thank you in advance!

Alon

**Comment by ithiele** [comment]
No models are also written in sbml format.

AGORA1 and 2 can be downloaded here:
https://vmh.life/files/reconstructions/

Note that MEMOTE only allows for comparing annotation features and limited organism-specific metabolic capabilities assessments. The latter one is really what you would like to compare.
